version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: course_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ratnadeep17/course-management-api:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/course_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  frontend:
    image: ratnadeep17/course-management-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
